# Mercedes-Benz Greener Manufacturing

importing the library "pandas" and "numpay"

### Project 1 - Mercedes-Benz Greener Manufacturing

DESCRIPTION
	
Reduce the time a Mercedes-Benz spends on the test bench.

    # Problem Statement Scenario:
	
        Since the first automobile, the Benz Patent Motor Car in 1886, Mercedes-Benz has stood for important automotive innovations. These include the passenger safety cell with the crumple zone, the airbag, and intelligent assistance systems. Mercedes-Benz applies for nearly 2000 patents per year, making the brand the European leader among premium carmakers. Mercedes-Benz cars are leaders in the premium car industry. With a huge selection of features and options, customers can choose the customized Mercedes-Benz of their dreams.

        To ensure the safety and reliability of every unique car configuration before they hit the road, Daimler’s engineers have developed a robust testing system. As one of the world’s biggest manufacturers of premium cars, safety and efficiency are paramount on Daimler’s production lines. However, optimizing the speed of their testing system for many possible feature combinations is complex and time-consuming without a powerful algorithmic approach.

        You are required to reduce the time that cars spend on the test bench. Others will work with a dataset representing different permutations of features in a Mercedes-Benz car to predict the time it takes to pass testing. Optimal algorithms will contribute to faster testing, resulting in lower carbon dioxide emissions without reducing Daimler’s standards.

	# Following actions should be performed:
	* If for any column(s), the variance is equal to zero, then you need to remove those variable(s).
	* Check for null and unique values for test and train sets
	* Apply label encoder.
	* Perform dimensionality reduction.
	* Predict your test_df values using xgboost

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

importng the train data structure

In [2]:
train=pd.read_csv("train.csv")
Test = pd.read_csv("test.csv")
train

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

### 1. If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

In [3]:
train.var()
#  RangeIndex: 4209
#  Columns: 378
#  dtypes: float64(1) int64(369), object(8)

ID      5.941936e+06
y       1.607667e+02
X10     1.313092e-02
X11     0.000000e+00
X12     6.945713e-02
            ...
X380    8.014579e-03
X382    7.546747e-03
X383    1.660732e-03
X384    4.750593e-04
X385    1.423823e-03
Length: 370, dtype: float64

In [4]:
Test.var()

ID      5.871311e+06
X10     1.865006e-02
X11     2.375861e-04
X12     6.885074e-02
X13     5.734498e-02
            ...
X380    8.014579e-03
X382    8.715481e-03
X383    4.750593e-04
X384    7.124196e-04
X385    1.660732e-03
Length: 369, dtype: float64

In [5]:
n = pd.DataFrame((train.var()==0), columns=["a"])
dr = n[n.a==True].T
dr

    X11   X93  X107  X233  X235  X268  X289  X290  X293  X297  X330  X347
a  True  True  True  True  True  True  True  True  True  True  True  True

In [6]:
list(dr.columns)

['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347']

In [7]:
train.drop(columns=list(dr.columns),inplace=True)
Test.drop(columns=list(dr.columns),inplace=True)

In [8]:
train

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

### 2. Check for null and unique values for test and train sets

### ------------------------------------------ For Train Data --------------------------------------------------

1 . find null values

In [9]:
#null values
train.isna().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 366, dtype: int64

In [10]:
# pd.DataFrame(train.isna().sum()>0)
n1 = pd.DataFrame((train.isna().sum()>0), columns=["a"])
dr1 = n1[n1.a==True]
dr1

Empty DataFrame
Columns: [a]
Index: []

#### hence there is no null values in train DataFrame

#### 2. Unique Values of Train sets

In [11]:
train_columns = train.columns
train_columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=366)

In [12]:
columns=[]                # define list       
counts=[]                  
unique =[]                
colm =train.columns
for i in colm:
    columns.append(i)
    a = train[i].nunique()
    counts.append(a)
    b=train[i].unique()
    unique.append(b)
    print("The no. of unique values of {} column is = {} \n  & unique values of {} column is = \n {} \n".format(i,train[i].nunique(),i,train[i].unique()))

The no. of unique values of ID column is = 4209
  & unique values of ID column is =
 [   0    6    7 ... 8412 8415 8417]

The no. of unique values of y column is = 2545
  & unique values of y column is =
 [130.81  88.53  76.26 ...  85.71 108.77  87.48]

The no. of unique values of X0 column is = 47
  & unique values of X0 column is =
 ['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab']

The no. of unique values of X1 column is = 27
  & unique values of X1 column is =
 ['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab']

The no. of unique values of X2 column is = 44
  & unique values of X2 column is =
 ['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar']

The no. of unique values of X3 column is = 7
  & unique values of X3 column is =
 ['a' 'e' 'c' 'f' 'd' 'b' 'g']

The no. of unique values of X4 column is = 4
  & unique values of X4 column is =
 ['d' 'b' 'c' 'a']

The no. of unique values of X5 column is = 29
  & unique values of X5 column is =
 ['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad' 'ae'
 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa']

The no. of unique values of X6 column is = 12
  & unique values of X6 column is =
 ['j' 'l' 'd' 'h' 'i' 'a' 'g' 'c' 'k' 'e' 'f' 'b']

The no. of unique values of X8 column is = 25
  & unique values of X8 column is =
 ['o' 'x' 'e' 'n' 's' 'a' 'h' 'p' 'm' 'k' 'd' 'i' 'v' 'j' 'b' 'q' 'w' 'g'
 'y' 'l' 'f' 'u' 'r' 't' 'c']

The no. of unique values of X10 column is = 2
  & unique values of X10 column is =
 [0 1]

The no. of unique values of X12 column is = 2
  & unique values of X12 column is =
 [0 1]

The no. of unique values of X13 column is = 2
  & unique values of X13 column is =
 [1 0]

The no. of unique values of X14 column is = 2
  & unique values of X14 column is =
 [0 1]

The no. of unique values of X15 column is = 2
  & unique values of X15 column is =
 [0 1]

The no. of unique values of X16 column is = 2
  & unique values of X16 column is =
 [0 1]

The no. of unique values of X17 column is = 2
  & unique values of X17 column is =
 [0 1]

The no. of unique values of X18 column is = 2
  & unique values of X18 column is =
 [1 0]

The no. of unique values of X19 column is = 2
  & unique values of X19 column is =
 [0 1]

The no. of unique values of X20 column is = 2
  & unique values of X20 column is =
 [0 1]

The no. of unique values of X21 column is = 2
  & unique values of X21 column is =
 [1 0]

The no. of unique values of X22 column is = 2
  & unique values of X22 column is =
 [0 1]

The no. of unique values of X23 column is = 2
  & unique values of X23 column is =
 [0 1]

The no. of unique values of X24 column is = 2
  & unique values of X24 column is =
 [0 1]

The no. of unique values of X26 column is = 2
  & unique values of X26 column is =
 [0 1]

The no. of unique values of X27 column is = 2
  & unique values of X27 column is =
 [0 1]

The no. of unique values of X28 column is = 2
  & unique values of X28 column is =
 [0 1]

The no. of unique values of X29 column is = 2
  & unique values of X29 column is =
 [0 1]

The no. of unique values of X30 column is = 2
  & unique values of X30 column is =
 [0 1]

The no. of unique values of X31 column is = 2
  & unique values of X31 column is =
 [1 0]

The no. of unique values of X32 column is = 2
  & unique values of X32 column is =
 [0 1]

The no. of unique values of X33 column is = 2
  & unique values of X33 column is =
 [0 1]

The no. of unique values of X34 column is = 2
  & unique values of X34 column is =
 [0 1]

The no. of unique values of X35 column is = 2
  & unique values of X35 column is =
 [1 0]

The no. of unique values of X36 column is = 2
  & unique values of X36 column is =
 [0 1]

The no. of unique values of X37 column is = 2
  & unique values of X37 column is =
 [1 0]

The no. of unique values of X38 column is = 2
  & unique values of X38 column is =
 [0 1]

The no. of unique values of X39 column is = 2
  & unique values of X39 column is =
 [0 1]

The no. of unique values of X40 column is = 2
  & unique values of X40 column is =
 [0 1]

The no. of unique values of X41 column is = 2
  & unique values of X41 column is =
 [0 1]

The no. of unique values of X42 column is = 2
  & unique values of X42 column is =
 [0 1]

The no. of unique values of X43 column is = 2
  & unique values of X43 column is =
 [0 1]

The no. of unique values of X44 column is = 2
  & unique values of X44 column is =
 [0 1]

The no. of unique values of X45 column is = 2
  & unique values of X45 column is =
 [0 1]

The no. of unique values of X46 column is = 2
  & unique values of X46 column is =
 [1 0]

The no. of unique values of X47 column is = 2
  & unique values of X47 column is =
 [0 1]

The no. of unique values of X48 column is = 2
  & unique values of X48 column is =
 [0 1]

The no. of unique values of X49 column is = 2
  & unique values of X49 column is =
 [0 1]

The no. of unique values of X50 column is = 2
  & unique values of X50 column is =
 [0 1]

The no. of unique values of X51 column is = 2
  & unique values of X51 column is =
 [0 1]

The no. of unique values of X52 column is = 2
  & unique values of X52 column is =
 [0 1]

The no. of unique values of X53 column is = 2
  & unique values of X53 column is =
 [0 1]

The no. of unique values of X54 column is = 2
  & unique values of X54 column is =
 [0 1]

The no. of unique values of X55 column is = 2
  & unique values of X55 column is =
 [0 1]

The no. of unique values of X56 column is = 2
  & unique values of X56 column is =
 [0 1]

The no. of unique values of X57 column is = 2
  & unique values of X57 column is =
 [0 1]

The no. of unique values of X58 column is = 2
  & unique values of X58 column is =
 [1 0]

The no. of unique values of X59 column is = 2
  & unique values of X59 column is =
 [0 1]

The no. of unique values of X60 column is = 2
  & unique values of X60 column is =
 [0 1]

The no. of unique values of X61 column is = 2
  & unique values of X61 column is =
 [0 1]

The no. of unique values of X62 column is = 2
  & unique values of X62 column is =
 [0 1]

The no. of unique values of X63 column is = 2
  & unique values of X63 column is =
 [0 1]

The no. of unique values of X64 column is = 2
  & unique values of X64 column is =
 [0 1]

The no. of unique values of X65 column is = 2
  & unique values of X65 column is =
 [0 1]

The no. of unique values of X66 column is = 2
  & unique values of X66 column is =
 [0 1]

The no. of unique values of X67 column is = 2
  & unique values of X67 column is =
 [0 1]

The no. of unique values of X68 column is = 2
  & unique values of X68 column is =
 [1 0]

The no. of unique values of X69 column is = 2
  & unique values of X69 column is =
 [0 1]

The no. of unique values of X70 column is = 2
  & unique values of X70 column is =
 [1 0]

The no. of unique values of X71 column is = 2
  & unique values of X71 column is =
 [0 1]

The no. of unique values of X73 column is = 2
  & unique values of X73 column is =
 [0 1]

The no. of unique values of X74 column is = 2
  & unique values of X74 column is =
 [1 0]

The no. of unique values of X75 column is = 2
  & unique values of X75 column is =
 [0 1]

The no. of unique values of X76 column is = 2
  & unique values of X76 column is =
 [0 1]

The no. of unique values of X77 column is = 2
  & unique values of X77 column is =
 [0 1]

The no. of unique values of X78 column is = 2
  & unique values of X78 column is =
 [0 1]

The no. of unique values of X79 column is = 2
  & unique values of X79 column is =
 [0 1]

The no. of unique values of X80 column is = 2
  & unique values of X80 column is =
 [0 1]

The no. of unique values of X81 column is = 2
  & unique values of X81 column is =
 [0 1]

The no. of unique values of X82 column is = 2
  & unique values of X82 column is =
 [0 1]

The no. of unique values of X83 column is = 2
  & unique values of X83 column is =
 [0 1]

The no. of unique values of X84 column is = 2
  & unique values of X84 column is =
 [0 1]

The no. of unique values of X85 column is = 2
  & unique values of X85 column is =
 [1 0]

The no. of unique values of X86 column is = 2
  & unique values of X86 column is =
 [0 1]

The no. of unique values of X87 column is = 2
  & unique values of X87 column is =
 [0 1]

The no. of unique values of X88 column is = 2
  & unique values of X88 column is =
 [0 1]

The no. of unique values of X89 column is = 2
  & unique values of X89 column is =
 [0 1]

The no. of unique values of X90 column is = 2
  & unique values of X90 column is =
 [0 1]

The no. of unique values of X91 column is = 2
  & unique values of X91 column is =
 [0 1]

The no. of unique values of X92 column is = 2
  & unique values of X92 column is =
 [0 1]

The no. of unique values of X94 column is = 2
  & unique values of X94 column is =
 [0 1]

The no. of unique values of X95 column is = 2
  & unique values of X95 column is =
 [0 1]

The no. of unique values of X96 column is = 2
  & unique values of X96 column is =
 [0 1]

The no. of unique values of X97 column is = 2
  & unique values of X97 column is =
 [0 1]

The no. of unique values of X98 column is = 2
  & unique values of X98 column is =
 [0 1]

The no. of unique values of X99 column is = 2
  & unique values of X99 column is =
 [0 1]

The no. of unique values of X100 column is = 2
  & unique values of X100 column is =
 [0 1]

The no. of unique values of X101 column is = 2
  & unique values of X101 column is =
 [0 1]

The no. of unique values of X102 column is = 2
  & unique values of X102 column is =
 [0 1]

The no. of unique values of X103 column is = 2
  & unique values of X103 column is =
 [0 1]

The no. of unique values of X104 column is = 2
  & unique values of X104 column is =
 [0 1]

The no. of unique values of X105 column is = 2
  & unique values of X105 column is =
 [0 1]

The no. of unique values of X106 column is = 2
  & unique values of X106 column is =
 [0 1]

The no. of unique values of X108 column is = 2
  & unique values of X108 column is =
 [0 1]

The no. of unique values of X109 column is = 2
  & unique values of X109 column is =
 [0 1]

The no. of unique values of X110 column is = 2
  & unique values of X110 column is =
 [0 1]

The no. of unique values of X111 column is = 2
  & unique values of X111 column is =
 [1 0]

The no. of unique values of X112 column is = 2
  & unique values of X112 column is =
 [0 1]

The no. of unique values of X113 column is = 2
  & unique values of X113 column is =
 [0 1]

The no. of unique values of X114 column is = 2
  & unique values of X114 column is =
 [1 0]

The no. of unique values of X115 column is = 2
  & unique values of X115 column is =
 [0 1]

The no. of unique values of X116 column is = 2
  & unique values of X116 column is =
 [1 0]

The no. of unique values of X117 column is = 2
  & unique values of X117 column is =
 [0 1]

The no. of unique values of X118 column is = 2
  & unique values of X118 column is =
 [1 0]

The no. of unique values of X119 column is = 2
  & unique values of X119 column is =
 [1 0]

The no. of unique values of X120 column is = 2
  & unique values of X120 column is =
 [1 0]

The no. of unique values of X122 column is = 2
  & unique values of X122 column is =
 [0 1]

The no. of unique values of X123 column is = 2
  & unique values of X123 column is =
 [0 1]

The no. of unique values of X124 column is = 2
  & unique values of X124 column is =
 [0 1]

The no. of unique values of X125 column is = 2
  & unique values of X125 column is =
 [0 1]

The no. of unique values of X126 column is = 2
  & unique values of X126 column is =
 [0 1]

The no. of unique values of X127 column is = 2
  & unique values of X127 column is =
 [0 1]

The no. of unique values of X128 column is = 2
  & unique values of X128 column is =
 [1 0]

The no. of unique values of X129 column is = 2
  & unique values of X129 column is =
 [0 1]

The no. of unique values of X130 column is = 2
  & unique values of X130 column is =
 [0 1]

The no. of unique values of X131 column is = 2
  & unique values of X131 column is =
 [1 0]

The no. of unique values of X132 column is = 2
  & unique values of X132 column is =
 [0 1]

The no. of unique values of X133 column is = 2
  & unique values of X133 column is =
 [0 1]

The no. of unique values of X134 column is = 2
  & unique values of X134 column is =
 [0 1]

The no. of unique values of X135 column is = 2
  & unique values of X135 column is =
 [0 1]

The no. of unique values of X136 column is = 2
  & unique values of X136 column is =
 [1 0]

The no. of unique values of X137 column is = 2
  & unique values of X137 column is =
 [1 0]

The no. of unique values of X138 column is = 2
  & unique values of X138 column is =
 [0 1]

The no. of unique values of X139 column is = 2
  & unique values of X139 column is =
 [0 1]

The no. of unique values of X140 column is = 2
  & unique values of X140 column is =
 [0 1]

The no. of unique values of X141 column is = 2
  & unique values of X141 column is =
 [0 1]

The no. of unique values of X142 column is = 2
  & unique values of X142 column is =
 [1 0]

The no. of unique values of X143 column is = 2
  & unique values of X143 column is =
 [0 1]

The no. of unique values of X144 column is = 2
  & unique values of X144 column is =
 [1 0]

The no. of unique values of X145 column is = 2
  & unique values of X145 column is =
 [0 1]

The no. of unique values of X146 column is = 2
  & unique values of X146 column is =
 [0 1]

The no. of unique values of X147 column is = 2
  & unique values of X147 column is =
 [0 1]

The no. of unique values of X148 column is = 2
  & unique values of X148 column is =
 [0 1]

The no. of unique values of X150 column is = 2
  & unique values of X150 column is =
 [1 0]

The no. of unique values of X151 column is = 2
  & unique values of X151 column is =
 [0 1]

The no. of unique values of X152 column is = 2
  & unique values of X152 column is =
 [0 1]

The no. of unique values of X153 column is = 2
  & unique values of X153 column is =
 [0 1]

The no. of unique values of X154 column is = 2
  & unique values of X154 column is =
 [0 1]

The no. of unique values of X155 column is = 2
  & unique values of X155 column is =
 [0 1]

The no. of unique values of X156 column is = 2
  & unique values of X156 column is =
 [1 0]

The no. of unique values of X157 column is = 2
  & unique values of X157 column is =
 [0 1]

The no. of unique values of X158 column is = 2
  & unique values of X158 column is =
 [0 1]

The no. of unique values of X159 column is = 2
  & unique values of X159 column is =
 [0 1]

The no. of unique values of X160 column is = 2
  & unique values of X160 column is =
 [0 1]

The no. of unique values of X161 column is = 2
  & unique values of X161 column is =
 [0 1]

The no. of unique values of X162 column is = 2
  & unique values of X162 column is =
 [0 1]

The no. of unique values of X163 column is = 2
  & unique values of X163 column is =
 [0 1]

The no. of unique values of X164 column is = 2
  & unique values of X164 column is =
 [0 1]

The no. of unique values of X165 column is = 2
  & unique values of X165 column is =
 [0 1]

The no. of unique values of X166 column is = 2
  & unique values of X166 column is =
 [0 1]

The no. of unique values of X167 column is = 2
  & unique values of X167 column is =
 [0 1]

The no. of unique values of X168 column is = 2
  & unique values of X168 column is =
 [0 1]

The no. of unique values of X169 column is = 2
  & unique values of X169 column is =
 [0 1]

The no. of unique values of X170 column is = 2
  & unique values of X170 column is =
 [1 0]

The no. of unique values of X171 column is = 2
  & unique values of X171 column is =
 [0 1]

The no. of unique values of X172 column is = 2
  & unique values of X172 column is =
 [0 1]

The no. of unique values of X173 column is = 2
  & unique values of X173 column is =
 [0 1]

The no. of unique values of X174 column is = 2
  & unique values of X174 column is =
 [0 1]

The no. of unique values of X175 column is = 2
  & unique values of X175 column is =
 [0 1]

The no. of unique values of X176 column is = 2
  & unique values of X176 column is =
 [0 1]

The no. of unique values of X177 column is = 2
  & unique values of X177 column is =
 [0 1]

The no. of unique values of X178 column is = 2
  & unique values of X178 column is =
 [0 1]

The no. of unique values of X179 column is = 2
  & unique values of X179 column is =
 [1 0]

The no. of unique values of X180 column is = 2
  & unique values of X180 column is =
 [0 1]

The no. of unique values of X181 column is = 2
  & unique values of X181 column is =
 [0 1]

The no. of unique values of X182 column is = 2
  & unique values of X182 column is =
 [0 1]

The no. of unique values of X183 column is = 2
  & unique values of X183 column is =
 [0 1]

The no. of unique values of X184 column is = 2
  & unique values of X184 column is =
 [1 0]

The no. of unique values of X185 column is = 2
  & unique values of X185 column is =
 [0 1]

The no. of unique values of X186 column is = 2
  & unique values of X186 column is =
 [0 1]

The no. of unique values of X187 column is = 2
  & unique values of X187 column is =
 [1 0]

The no. of unique values of X189 column is = 2
  & unique values of X189 column is =
 [1 0]

The no. of unique values of X190 column is = 2
  & unique values of X190 column is =
 [0 1]

The no. of unique values of X191 column is = 2
  & unique values of X191 column is =
 [0 1]

The no. of unique values of X192 column is = 2
  & unique values of X192 column is =
 [0 1]

The no. of unique values of X194 column is = 2
  & unique values of X194 column is =
 [1 0]

The no. of unique values of X195 column is = 2
  & unique values of X195 column is =
 [0 1]

The no. of unique values of X196 column is = 2
  & unique values of X196 column is =
 [0 1]

The no. of unique values of X197 column is = 2
  & unique values of X197 column is =
 [0 1]

The no. of unique values of X198 column is = 2
  & unique values of X198 column is =
 [0 1]

The no. of unique values of X199 column is = 2
  & unique values of X199 column is =
 [0 1]

The no. of unique values of X200 column is = 2
  & unique values of X200 column is =
 [0 1]

The no. of unique values of X201 column is = 2
  & unique values of X201 column is =
 [0 1]

The no. of unique values of X202 column is = 2
  & unique values of X202 column is =
 [0 1]

The no. of unique values of X203 column is = 2
  & unique values of X203 column is =
 [0 1]

The no. of unique values of X204 column is = 2
  & unique values of X204 column is =
 [1 0]

The no. of unique values of X205 column is = 2
  & unique values of X205 column is =
 [0 1]

The no. of unique values of X206 column is = 2
  & unique values of X206 column is =
 [0 1]

The no. of unique values of X207 column is = 2
  & unique values of X207 column is =
 [0 1]

The no. of unique values of X208 column is = 2
  & unique values of X208 column is =
 [0 1]

The no. of unique values of X209 column is = 2
  & unique values of X209 column is =
 [1 0]

The no. of unique values of X210 column is = 2
  & unique values of X210 column is =
 [0 1]

The no. of unique values of X211 column is = 2
  & unique values of X211 column is =
 [0 1]

The no. of unique values of X212 column is = 2
  & unique values of X212 column is =
 [0 1]

The no. of unique values of X213 column is = 2
  & unique values of X213 column is =
 [0 1]

The no. of unique values of X214 column is = 2
  & unique values of X214 column is =
 [0 1]

The no. of unique values of X215 column is = 2
  & unique values of X215 column is =
 [0 1]

The no. of unique values of X216 column is = 2
  & unique values of X216 column is =
 [0 1]

The no. of unique values of X217 column is = 2
  & unique values of X217 column is =
 [0 1]

The no. of unique values of X218 column is = 2
  & unique values of X218 column is =
 [0 1]

The no. of unique values of X219 column is = 2
  & unique values of X219 column is =
 [0 1]

The no. of unique values of X220 column is = 2
  & unique values of X220 column is =
 [1 0]

The no. of unique values of X221 column is = 2
  & unique values of X221 column is =
 [0 1]

The no. of unique values of X222 column is = 2
  & unique values of X222 column is =
 [0 1]

The no. of unique values of X223 column is = 2
  & unique values of X223 column is =
 [0 1]

The no. of unique values of X224 column is = 2
  & unique values of X224 column is =
 [0 1]

The no. of unique values of X225 column is = 2
  & unique values of X225 column is =
 [0 1]

The no. of unique values of X226 column is = 2
  & unique values of X226 column is =
 [0 1]

The no. of unique values of X227 column is = 2
  & unique values of X227 column is =
 [0 1]

The no. of unique values of X228 column is = 2
  & unique values of X228 column is =
 [0 1]

The no. of unique values of X229 column is = 2
  & unique values of X229 column is =
 [0 1]

The no. of unique values of X230 column is = 2
  & unique values of X230 column is =
 [0 1]

The no. of unique values of X231 column is = 2
  & unique values of X231 column is =
 [0 1]

The no. of unique values of X232 column is = 2
  & unique values of X232 column is =
 [0 1]

The no. of unique values of X234 column is = 2
  & unique values of X234 column is =
 [1 0]

The no. of unique values of X236 column is = 2
  & unique values of X236 column is =
 [0 1]

The no. of unique values of X237 column is = 2
  & unique values of X237 column is =
 [1 0]

The no. of unique values of X238 column is = 2
  & unique values of X238 column is =
 [0 1]

The no. of unique values of X239 column is = 2
  & unique values of X239 column is =
 [0 1]

The no. of unique values of X240 column is = 2
  & unique values of X240 column is =
 [0 1]

The no. of unique values of X241 column is = 2
  & unique values of X241 column is =
 [0 1]

The no. of unique values of X242 column is = 2
  & unique values of X242 column is =
 [0 1]

The no. of unique values of X243 column is = 2
  & unique values of X243 column is =
 [0 1]

The no. of unique values of X244 column is = 2
  & unique values of X244 column is =
 [0 1]

The no. of unique values of X245 column is = 2
  & unique values of X245 column is =
 [0 1]

The no. of unique values of X246 column is = 2
  & unique values of X246 column is =
 [0 1]

The no. of unique values of X247 column is = 2
  & unique values of X247 column is =
 [0 1]

The no. of unique values of X248 column is = 2
  & unique values of X248 column is =
 [0 1]

The no. of unique values of X249 column is = 2
  & unique values of X249 column is =
 [0 1]

The no. of unique values of X250 column is = 2
  & unique values of X250 column is =
 [0 1]

The no. of unique values of X251 column is = 2
  & unique values of X251 column is =
 [0 1]

The no. of unique values of X252 column is = 2
  & unique values of X252 column is =
 [0 1]

The no. of unique values of X253 column is = 2
  & unique values of X253 column is =
 [0 1]

The no. of unique values of X254 column is = 2
  & unique values of X254 column is =
 [0 1]

The no. of unique values of X255 column is = 2
  & unique values of X255 column is =
 [0 1]

The no. of unique values of X256 column is = 2
  & unique values of X256 column is =
 [0 1]

The no. of unique values of X257 column is = 2
  & unique values of X257 column is =
 [0 1]

The no. of unique values of X258 column is = 2
  & unique values of X258 column is =
 [0 1]

The no. of unique values of X259 column is = 2
  & unique values of X259 column is =
 [0 1]

The no. of unique values of X260 column is = 2
  & unique values of X260 column is =
 [0 1]

The no. of unique values of X261 column is = 2
  & unique values of X261 column is =
 [0 1]

The no. of unique values of X262 column is = 2
  & unique values of X262 column is =
 [1 0]

The no. of unique values of X263 column is = 2
  & unique values of X263 column is =
 [1 0]

The no. of unique values of X264 column is = 2
  & unique values of X264 column is =
 [0 1]

The no. of unique values of X265 column is = 2
  & unique values of X265 column is =
 [0 1]

The no. of unique values of X266 column is = 2
  & unique values of X266 column is =
 [1 0]

The no. of unique values of X267 column is = 2
  & unique values of X267 column is =
 [0 1]

The no. of unique values of X269 column is = 2
  & unique values of X269 column is =
 [0 1]

The no. of unique values of X270 column is = 2
  & unique values of X270 column is =
 [0 1]

The no. of unique values of X271 column is = 2
  & unique values of X271 column is =
 [0 1]

The no. of unique values of X272 column is = 2
  & unique values of X272 column is =
 [0 1]

The no. of unique values of X273 column is = 2
  & unique values of X273 column is =
 [1 0]

The no. of unique values of X274 column is = 2
  & unique values of X274 column is =
 [0 1]

The no. of unique values of X275 column is = 2
  & unique values of X275 column is =
 [1 0]

The no. of unique values of X276 column is = 2
  & unique values of X276 column is =
 [0 1]

The no. of unique values of X277 column is = 2
  & unique values of X277 column is =
 [0 1]

The no. of unique values of X278 column is = 2
  & unique values of X278 column is =
 [0 1]

The no. of unique values of X279 column is = 2
  & unique values of X279 column is =
 [0 1]

The no. of unique values of X280 column is = 2
  & unique values of X280 column is =
 [0 1]

The no. of unique values of X281 column is = 2
  & unique values of X281 column is =
 [0 1]

The no. of unique values of X282 column is = 2
  & unique values of X282 column is =
 [0 1]

The no. of unique values of X283 column is = 2
  & unique values of X283 column is =
 [0 1]

The no. of unique values of X284 column is = 2
  & unique values of X284 column is =
 [0 1]

The no. of unique values of X285 column is = 2
  & unique values of X285 column is =
 [1 0]

The no. of unique values of X286 column is = 2
  & unique values of X286 column is =
 [0 1]

The no. of unique values of X287 column is = 2
  & unique values of X287 column is =
 [0 1]

The no. of unique values of X288 column is = 2
  & unique values of X288 column is =
 [0 1]

The no. of unique values of X291 column is = 2
  & unique values of X291 column is =
 [0 1]

The no. of unique values of X292 column is = 2
  & unique values of X292 column is =
 [0 1]

The no. of unique values of X294 column is = 2
  & unique values of X294 column is =
 [0 1]

The no. of unique values of X295 column is = 2
  & unique values of X295 column is =
 [0 1]

The no. of unique values of X296 column is = 2
  & unique values of X296 column is =
 [0 1]

The no. of unique values of X298 column is = 2
  & unique values of X298 column is =
 [0 1]

The no. of unique values of X299 column is = 2
  & unique values of X299 column is =
 [0 1]

The no. of unique values of X300 column is = 2
  & unique values of X300 column is =
 [0 1]

The no. of unique values of X301 column is = 2
  & unique values of X301 column is =
 [0 1]

The no. of unique values of X302 column is = 2
  & unique values of X302 column is =
 [0 1]

The no. of unique values of X304 column is = 2
  & unique values of X304 column is =
 [0 1]

The no. of unique values of X305 column is = 2
  & unique values of X305 column is =
 [0 1]

The no. of unique values of X306 column is = 2
  & unique values of X306 column is =
 [1 0]

The no. of unique values of X307 column is = 2
  & unique values of X307 column is =
 [0 1]

The no. of unique values of X308 column is = 2
  & unique values of X308 column is =
 [0 1]

The no. of unique values of X309 column is = 2
  & unique values of X309 column is =
 [0 1]

The no. of unique values of X310 column is = 2
  & unique values of X310 column is =
 [0 1]

The no. of unique values of X311 column is = 2
  & unique values of X311 column is =
 [0 1]

The no. of unique values of X312 column is = 2
  & unique values of X312 column is =
 [0 1]

The no. of unique values of X313 column is = 2
  & unique values of X313 column is =
 [0 1]

The no. of unique values of X314 column is = 2
  & unique values of X314 column is =
 [0 1]

The no. of unique values of X315 column is = 2
  & unique values of X315 column is =
 [0 1]

The no. of unique values of X316 column is = 2
  & unique values of X316 column is =
 [1 0]

The no. of unique values of X317 column is = 2
  & unique values of X317 column is =
 [0 1]

The no. of unique values of X318 column is = 2
  & unique values of X318 column is =
 [0 1]

The no. of unique values of X319 column is = 2
  & unique values of X319 column is =
 [0 1]

The no. of unique values of X320 column is = 2
  & unique values of X320 column is =
 [0 1]

The no. of unique values of X321 column is = 2
  & unique values of X321 column is =
 [0 1]

The no. of unique values of X322 column is = 2
  & unique values of X322 column is =
 [0 1]

The no. of unique values of X323 column is = 2
  & unique values of X323 column is =
 [0 1]

The no. of unique values of X324 column is = 2
  & unique values of X324 column is =
 [1 0]

The no. of unique values of X325 column is = 2
  & unique values of X325 column is =
 [0 1]

The no. of unique values of X326 column is = 2
  & unique values of X326 column is =
 [0 1]

The no. of unique values of X327 column is = 2
  & unique values of X327 column is =
 [1 0]

The no. of unique values of X328 column is = 2
  & unique values of X328 column is =
 [0 1]

The no. of unique values of X329 column is = 2
  & unique values of X329 column is =
 [1 0]

The no. of unique values of X331 column is = 2
  & unique values of X331 column is =
 [0 1]

The no. of unique values of X332 column is = 2
  & unique values of X332 column is =
 [0 1]

The no. of unique values of X333 column is = 2
  & unique values of X333 column is =
 [0 1]

The no. of unique values of X334 column is = 2
  & unique values of X334 column is =
 [1 0]

The no. of unique values of X335 column is = 2
  & unique values of X335 column is =
 [0 1]

The no. of unique values of X336 column is = 2
  & unique values of X336 column is =
 [0 1]

The no. of unique values of X337 column is = 2
  & unique values of X337 column is =
 [0 1]

The no. of unique values of X338 column is = 2
  & unique values of X338 column is =
 [0 1]

The no. of unique values of X339 column is = 2
  & unique values of X339 column is =
 [0 1]

The no. of unique values of X340 column is = 2
  & unique values of X340 column is =
 [0 1]

The no. of unique values of X341 column is = 2
  & unique values of X341 column is =
 [0 1]

The no. of unique values of X342 column is = 2
  & unique values of X342 column is =
 [0 1]

The no. of unique values of X343 column is = 2
  & unique values of X343 column is =
 [0 1]

The no. of unique values of X344 column is = 2
  & unique values of X344 column is =
 [0 1]

The no. of unique values of X345 column is = 2
  & unique values of X345 column is =
 [0 1]

The no. of unique values of X346 column is = 2
  & unique values of X346 column is =
 [0 1]

The no. of unique values of X348 column is = 2
  & unique values of X348 column is =
 [0 1]

The no. of unique values of X349 column is = 2
  & unique values of X349 column is =
 [0 1]

The no. of unique values of X350 column is = 2
  & unique values of X350 column is =
 [0 1]

The no. of unique values of X351 column is = 2
  & unique values of X351 column is =
 [0 1]

The no. of unique values of X352 column is = 2
  & unique values of X352 column is =
 [0 1]

The no. of unique values of X353 column is = 2
  & unique values of X353 column is =
 [0 1]

The no. of unique values of X354 column is = 2
  & unique values of X354 column is =
 [1 0]

The no. of unique values of X355 column is = 2
  & unique values of X355 column is =
 [0 1]

The no. of unique values of X356 column is = 2
  & unique values of X356 column is =
 [0 1]

The no. of unique values of X357 column is = 2
  & unique values of X357 column is =
 [0 1]

The no. of unique values of X358 column is = 2
  & unique values of X358 column is =
 [0 1]

The no. of unique values of X359 column is = 2
  & unique values of X359 column is =
 [0 1]

The no. of unique values of X360 column is = 2
  & unique values of X360 column is =
 [0 1]

The no. of unique values of X361 column is = 2
  & unique values of X361 column is =
 [1 0]

The no. of unique values of X362 column is = 2
  & unique values of X362 column is =
 [0 1]

The no. of unique values of X363 column is = 2
  & unique values of X363 column is =
 [0 1]

The no. of unique values of X364 column is = 2
  & unique values of X364 column is =
 [0 1]

The no. of unique values of X365 column is = 2
  & unique values of X365 column is =
 [0 1]

The no. of unique values of X366 column is = 2
  & unique values of X366 column is =
 [0 1]

The no. of unique values of X367 column is = 2
  & unique values of X367 column is =
 [0 1]

The no. of unique values of X368 column is = 2
  & unique values of X368 column is =
 [0 1]

The no. of unique values of X369 column is = 2
  & unique values of X369 column is =
 [0 1]

The no. of unique values of X370 column is = 2
  & unique values of X370 column is =
 [0 1]

The no. of unique values of X371 column is = 2
  & unique values of X371 column is =
 [0 1]

The no. of unique values of X372 column is = 2
  & unique values of X372 column is =
 [0 1]

The no. of unique values of X373 column is = 2
  & unique values of X373 column is =
 [0 1]

The no. of unique values of X374 column is = 2
  & unique values of X374 column is =
 [0 1]

The no. of unique values of X375 column is = 2
  & unique values of X375 column is =
 [0 1]

The no. of unique values of X376 column is = 2
  & unique values of X376 column is =
 [0 1]

The no. of unique values of X377 column is = 2
  & unique values of X377 column is =
 [1 0]

The no. of unique values of X378 column is = 2
  & unique values of X378 column is =
 [0 1]

The no. of unique values of X379 column is = 2
  & unique values of X379 column is =
 [0 1]

The no. of unique values of X380 column is = 2
  & unique values of X380 column is =
 [0 1]

The no. of unique values of X382 column is = 2
  & unique values of X382 column is =
 [0 1]

The no. of unique values of X383 column is = 2
  & unique values of X383 column is =
 [0 1]

The no. of unique values of X384 column is = 2
  & unique values of X384 column is =
 [0 1]

The no. of unique values of X385 column is = 2
  & unique values of X385 column is =
 [0 1]

In [13]:
# Making DataFrame accoeding to unique value

train_unique_info =pd.DataFrame({"columns":columns, 
              "counts":counts,
               "unique":unique})

In [14]:
train_unique_info.head()

  columns  counts                                             unique
0      ID    4209  [0, 6, 7, 9, 13, 18, 24, 25, 27, 30, 31, 32, 3...
1       y    2545  [130.81, 88.53, 76.26, 80.62, 78.02, 92.93, 12...
2      X0      47  [k, az, t, al, o, w, j, h, s, n, ay, f, x, y, ...
3      X1      27  [v, t, w, b, r, l, s, aa, c, a, e, h, z, j, o,...
4      X2      44  [at, av, n, e, as, aq, r, ai, ak, m, a, k, ae,...

### ------------------------------------------ For Test Data --------------------------------------------------

1 . find null values

In [15]:
Test.isnull().sum()

ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 365, dtype: int64

#### hence there is no null values in test DataFrame

2. Unique Values of Train sets

In [16]:
test_columns = Test.columns
test_columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=365)

In [20]:
columns_test=[]                # define list       
counts_test=[]                  
unique_test =[]                
colm =Test.columns
for i in colm:
    columns_test.append(i)
    a = Test[i].nunique()
    counts_test.append(a)
    b=Test[i].unique()
    unique_test.append(b)
    print("The no. of unique values of {} column is = {} \n  & unique values of {} column is = \n {} \n".format(i,Test[i].nunique(),i,Test[i].unique()))

The no. of unique values of ID column is = 4209
  & unique values of ID column is =
 [   1    2    3 ... 8413 8414 8416]

The no. of unique values of X0 column is = 49
  & unique values of X0 column is =
 ['az' 't' 'w' 'y' 'x' 'f' 'ap' 'o' 'ay' 'al' 'h' 'z' 'aj' 'd' 'v' 'ak'
 'ba' 'n' 'j' 's' 'af' 'ax' 'at' 'aq' 'av' 'm' 'k' 'a' 'e' 'ai' 'i' 'ag'
 'b' 'am' 'aw' 'as' 'r' 'ao' 'u' 'l' 'c' 'ad' 'au' 'bc' 'g' 'an' 'ae' 'p'
 'bb']

The no. of unique values of X1 column is = 27
  & unique values of X1 column is =
 ['v' 'b' 'l' 's' 'aa' 'r' 'a' 'i' 'p' 'c' 'o' 'm' 'z' 'e' 'h' 'w' 'g' 'k'
 'y' 't' 'u' 'd' 'j' 'q' 'n' 'f' 'ab']

The no. of unique values of X2 column is = 45
  & unique values of X2 column is =
 ['n' 'ai' 'as' 'ae' 's' 'b' 'e' 'ak' 'm' 'a' 'aq' 'ag' 'r' 'k' 'aj' 'ay'
 'ao' 'an' 'ac' 'af' 'ax' 'h' 'i' 'f' 'ap' 'p' 'au' 't' 'z' 'y' 'aw' 'd'
 'at' 'g' 'am' 'j' 'x' 'ab' 'w' 'q' 'ah' 'ad' 'al' 'av' 'u']

The no. of unique values of X3 column is = 7
  & unique values of X3 column is =
 ['f' 'a' 'c' 'e' 'd' 'g' 'b']

The no. of unique values of X4 column is = 4
  & unique values of X4 column is =
 ['d' 'b' 'a' 'c']

The no. of unique values of X5 column is = 32
  & unique values of X5 column is =
 ['t' 'b' 'a' 'z' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac'
 'ad' 'ae' 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa']

The no. of unique values of X6 column is = 12
  & unique values of X6 column is =
 ['a' 'g' 'j' 'l' 'i' 'd' 'f' 'h' 'c' 'k' 'e' 'b']

The no. of unique values of X8 column is = 25
  & unique values of X8 column is =
 ['w' 'y' 'j' 'n' 'm' 's' 'a' 'v' 'r' 'o' 't' 'h' 'c' 'k' 'p' 'u' 'd' 'g'
 'b' 'q' 'e' 'l' 'f' 'i' 'x']

The no. of unique values of X10 column is = 2
  & unique values of X10 column is =
 [0 1]

The no. of unique values of X12 column is = 2
  & unique values of X12 column is =
 [0 1]

The no. of unique values of X13 column is = 2
  & unique values of X13 column is =
 [0 1]

The no. of unique values of X14 column is = 2
  & unique values of X14 column is =
 [0 1]

The no. of unique values of X15 column is = 2
  & unique values of X15 column is =
 [0 1]

The no. of unique values of X16 column is = 2
  & unique values of X16 column is =
 [0 1]

The no. of unique values of X17 column is = 2
  & unique values of X17 column is =
 [0 1]

The no. of unique values of X18 column is = 2
  & unique values of X18 column is =
 [0 1]

The no. of unique values of X19 column is = 2
  & unique values of X19 column is =
 [0 1]

The no. of unique values of X20 column is = 2
  & unique values of X20 column is =
 [0 1]

The no. of unique values of X21 column is = 2
  & unique values of X21 column is =
 [0 1]

The no. of unique values of X22 column is = 2
  & unique values of X22 column is =
 [0 1]

The no. of unique values of X23 column is = 2
  & unique values of X23 column is =
 [0 1]

The no. of unique values of X24 column is = 2
  & unique values of X24 column is =
 [0 1]

The no. of unique values of X26 column is = 2
  & unique values of X26 column is =
 [0 1]

The no. of unique values of X27 column is = 2
  & unique values of X27 column is =
 [1 0]

The no. of unique values of X28 column is = 2
  & unique values of X28 column is =
 [1 0]

The no. of unique values of X29 column is = 2
  & unique values of X29 column is =
 [1 0]

The no. of unique values of X30 column is = 2
  & unique values of X30 column is =
 [0 1]

The no. of unique values of X31 column is = 2
  & unique values of X31 column is =
 [1 0]

The no. of unique values of X32 column is = 2
  & unique values of X32 column is =
 [0 1]

The no. of unique values of X33 column is = 2
  & unique values of X33 column is =
 [0 1]

The no. of unique values of X34 column is = 2
  & unique values of X34 column is =
 [0 1]

The no. of unique values of X35 column is = 2
  & unique values of X35 column is =
 [1 0]

The no. of unique values of X36 column is = 2
  & unique values of X36 column is =
 [0 1]

The no. of unique values of X37 column is = 2
  & unique values of X37 column is =
 [1 0]

The no. of unique values of X38 column is = 2
  & unique values of X38 column is =
 [0 1]

The no. of unique values of X39 column is = 2
  & unique values of X39 column is =
 [0 1]

The no. of unique values of X40 column is = 2
  & unique values of X40 column is =
 [0 1]

The no. of unique values of X41 column is = 2
  & unique values of X41 column is =
 [0 1]

The no. of unique values of X42 column is = 2
  & unique values of X42 column is =
 [0 1]

The no. of unique values of X43 column is = 2
  & unique values of X43 column is =
 [1 0]

The no. of unique values of X44 column is = 2
  & unique values of X44 column is =
 [0 1]

The no. of unique values of X45 column is = 2
  & unique values of X45 column is =
 [0 1]

The no. of unique values of X46 column is = 2
  & unique values of X46 column is =
 [1 0]

The no. of unique values of X47 column is = 2
  & unique values of X47 column is =
 [0 1]

The no. of unique values of X48 column is = 2
  & unique values of X48 column is =
 [0 1]

The no. of unique values of X49 column is = 2
  & unique values of X49 column is =
 [0 1]

The no. of unique values of X50 column is = 2
  & unique values of X50 column is =
 [0 1]

The no. of unique values of X51 column is = 2
  & unique values of X51 column is =
 [0 1]

The no. of unique values of X52 column is = 2
  & unique values of X52 column is =
 [0 1]

The no. of unique values of X53 column is = 2
  & unique values of X53 column is =
 [0 1]

The no. of unique values of X54 column is = 2
  & unique values of X54 column is =
 [1 0]

The no. of unique values of X55 column is = 2
  & unique values of X55 column is =
 [0 1]

The no. of unique values of X56 column is = 2
  & unique values of X56 column is =
 [0 1]

The no. of unique values of X57 column is = 2
  & unique values of X57 column is =
 [0 1]

The no. of unique values of X58 column is = 2
  & unique values of X58 column is =
 [0 1]

The no. of unique values of X59 column is = 2
  & unique values of X59 column is =
 [0 1]

The no. of unique values of X60 column is = 2
  & unique values of X60 column is =
 [0 1]

The no. of unique values of X61 column is = 2
  & unique values of X61 column is =
 [1 0]

The no. of unique values of X62 column is = 2
  & unique values of X62 column is =
 [0 1]

The no. of unique values of X63 column is = 2
  & unique values of X63 column is =
 [0 1]

The no. of unique values of X64 column is = 2
  & unique values of X64 column is =
 [0 1]

The no. of unique values of X65 column is = 2
  & unique values of X65 column is =
 [0 1]

The no. of unique values of X66 column is = 2
  & unique values of X66 column is =
 [0 1]

The no. of unique values of X67 column is = 2
  & unique values of X67 column is =
 [0 1]

The no. of unique values of X68 column is = 2
  & unique values of X68 column is =
 [0 1]

The no. of unique values of X69 column is = 2
  & unique values of X69 column is =
 [0 1]

The no. of unique values of X70 column is = 2
  & unique values of X70 column is =
 [1 0]

The no. of unique values of X71 column is = 2
  & unique values of X71 column is =
 [0 1]

The no. of unique values of X73 column is = 2
  & unique values of X73 column is =
 [0 1]

The no. of unique values of X74 column is = 2
  & unique values of X74 column is =
 [1 0]

The no. of unique values of X75 column is = 2
  & unique values of X75 column is =
 [0 1]

The no. of unique values of X76 column is = 2
  & unique values of X76 column is =
 [1 0]

The no. of unique values of X77 column is = 2
  & unique values of X77 column is =
 [0 1]

The no. of unique values of X78 column is = 2
  & unique values of X78 column is =
 [0 1]

The no. of unique values of X79 column is = 2
  & unique values of X79 column is =
 [0 1]

The no. of unique values of X80 column is = 2
  & unique values of X80 column is =
 [1 0]

The no. of unique values of X81 column is = 2
  & unique values of X81 column is =
 [0 1]

The no. of unique values of X82 column is = 2
  & unique values of X82 column is =
 [0 1]

The no. of unique values of X83 column is = 2
  & unique values of X83 column is =
 [0 1]

The no. of unique values of X84 column is = 2
  & unique values of X84 column is =
 [0 1]

The no. of unique values of X85 column is = 2
  & unique values of X85 column is =
 [0 1]

The no. of unique values of X86 column is = 2
  & unique values of X86 column is =
 [0 1]

The no. of unique values of X87 column is = 2
  & unique values of X87 column is =
 [0 1]

The no. of unique values of X88 column is = 2
  & unique values of X88 column is =
 [0 1]

The no. of unique values of X89 column is = 2
  & unique values of X89 column is =
 [0 1]

The no. of unique values of X90 column is = 2
  & unique values of X90 column is =
 [0 1]

The no. of unique values of X91 column is = 2
  & unique values of X91 column is =
 [0 1]

The no. of unique values of X92 column is = 2
  & unique values of X92 column is =
 [0 1]

The no. of unique values of X94 column is = 2
  & unique values of X94 column is =
 [0 1]

The no. of unique values of X95 column is = 2
  & unique values of X95 column is =
 [0 1]

The no. of unique values of X96 column is = 2
  & unique values of X96 column is =
 [1 0]

The no. of unique values of X97 column is = 2
  & unique values of X97 column is =
 [0 1]

The no. of unique values of X98 column is = 2
  & unique values of X98 column is =
 [1 0]

The no. of unique values of X99 column is = 2
  & unique values of X99 column is =
 [0 1]

The no. of unique values of X100 column is = 2
  & unique values of X100 column is =
 [0 1]

The no. of unique values of X101 column is = 2
  & unique values of X101 column is =
 [1 0]

The no. of unique values of X102 column is = 2
  & unique values of X102 column is =
 [0 1]

The no. of unique values of X103 column is = 2
  & unique values of X103 column is =
 [0 1]

The no. of unique values of X104 column is = 2
  & unique values of X104 column is =
 [0 1]

The no. of unique values of X105 column is = 2
  & unique values of X105 column is =
 [0 1]

The no. of unique values of X106 column is = 2
  & unique values of X106 column is =
 [0 1]

The no. of unique values of X108 column is = 2
  & unique values of X108 column is =
 [0 1]

The no. of unique values of X109 column is = 2
  & unique values of X109 column is =
 [0 1]

The no. of unique values of X110 column is = 2
  & unique values of X110 column is =
 [0 1]

The no. of unique values of X111 column is = 2
  & unique values of X111 column is =
 [1 0]

The no. of unique values of X112 column is = 2
  & unique values of X112 column is =
 [0 1]

The no. of unique values of X113 column is = 2
  & unique values of X113 column is =
 [0 1]

The no. of unique values of X114 column is = 2
  & unique values of X114 column is =
 [1 0]

The no. of unique values of X115 column is = 2
  & unique values of X115 column is =
 [0 1]

The no. of unique values of X116 column is = 2
  & unique values of X116 column is =
 [0 1]

The no. of unique values of X117 column is = 2
  & unique values of X117 column is =
 [0 1]

The no. of unique values of X118 column is = 2
  & unique values of X118 column is =
 [0 1]

The no. of unique values of X119 column is = 2
  & unique values of X119 column is =
 [0 1]

The no. of unique values of X120 column is = 2
  & unique values of X120 column is =
 [0 1]

The no. of unique values of X122 column is = 2
  & unique values of X122 column is =
 [0 1]

The no. of unique values of X123 column is = 2
  & unique values of X123 column is =
 [0 1]

The no. of unique values of X124 column is = 2
  & unique values of X124 column is =
 [0 1]

The no. of unique values of X125 column is = 2
  & unique values of X125 column is =
 [0 1]

The no. of unique values of X126 column is = 2
  & unique values of X126 column is =
 [0 1]

The no. of unique values of X127 column is = 2
  & unique values of X127 column is =
 [0 1]

The no. of unique values of X128 column is = 2
  & unique values of X128 column is =
 [1 0]

The no. of unique values of X129 column is = 2
  & unique values of X129 column is =
 [0 1]

The no. of unique values of X130 column is = 2
  & unique values of X130 column is =
 [0 1]

The no. of unique values of X131 column is = 2
  & unique values of X131 column is =
 [0 1]

The no. of unique values of X132 column is = 2
  & unique values of X132 column is =
 [1 0]

The no. of unique values of X133 column is = 2
  & unique values of X133 column is =
 [0 1]

The no. of unique values of X134 column is = 2
  & unique values of X134 column is =
 [0 1]

The no. of unique values of X135 column is = 2
  & unique values of X135 column is =
 [0 1]

The no. of unique values of X136 column is = 2
  & unique values of X136 column is =
 [0 1]

The no. of unique values of X137 column is = 2
  & unique values of X137 column is =
 [0 1]

The no. of unique values of X138 column is = 2
  & unique values of X138 column is =
 [0 1]

The no. of unique values of X139 column is = 2
  & unique values of X139 column is =
 [0 1]

The no. of unique values of X140 column is = 2
  & unique values of X140 column is =
 [0 1]

The no. of unique values of X141 column is = 2
  & unique values of X141 column is =
 [0 1]

The no. of unique values of X142 column is = 2
  & unique values of X142 column is =
 [0 1]

The no. of unique values of X143 column is = 2
  & unique values of X143 column is =
 [0 1]

The no. of unique values of X144 column is = 2
  & unique values of X144 column is =
 [1 0]

The no. of unique values of X145 column is = 2
  & unique values of X145 column is =
 [0 1]

The no. of unique values of X146 column is = 2
  & unique values of X146 column is =
 [0 1]

The no. of unique values of X147 column is = 2
  & unique values of X147 column is =
 [0 1]

The no. of unique values of X148 column is = 2
  & unique values of X148 column is =
 [1 0]

The no. of unique values of X150 column is = 2
  & unique values of X150 column is =
 [1 0]

The no. of unique values of X151 column is = 2
  & unique values of X151 column is =
 [0 1]

The no. of unique values of X152 column is = 2
  & unique values of X152 column is =
 [0 1]

The no. of unique values of X153 column is = 2
  & unique values of X153 column is =
 [0 1]

The no. of unique values of X154 column is = 2
  & unique values of X154 column is =
 [0 1]

The no. of unique values of X155 column is = 2
  & unique values of X155 column is =
 [0 1]

The no. of unique values of X156 column is = 2
  & unique values of X156 column is =
 [0 1]

The no. of unique values of X157 column is = 2
  & unique values of X157 column is =
 [1 0]

The no. of unique values of X158 column is = 2
  & unique values of X158 column is =
 [1 0]

The no. of unique values of X159 column is = 2
  & unique values of X159 column is =
 [0 1]

The no. of unique values of X160 column is = 2
  & unique values of X160 column is =
 [0 1]

The no. of unique values of X161 column is = 2
  & unique values of X161 column is =
 [0 1]

The no. of unique values of X162 column is = 2
  & unique values of X162 column is =
 [1 0]

The no. of unique values of X163 column is = 2
  & unique values of X163 column is =
 [0 1]

The no. of unique values of X164 column is = 2
  & unique values of X164 column is =
 [0 1]

The no. of unique values of X165 column is = 2
  & unique values of X165 column is =
 [0 1]

The no. of unique values of X166 column is = 2
  & unique values of X166 column is =
 [1 0]

The no. of unique values of X167 column is = 2
  & unique values of X167 column is =
 [0 1]

The no. of unique values of X168 column is = 2
  & unique values of X168 column is =
 [0 1]

The no. of unique values of X169 column is = 2
  & unique values of X169 column is =
 [0 1]

The no. of unique values of X170 column is = 2
  & unique values of X170 column is =
 [0 1]

The no. of unique values of X171 column is = 2
  & unique values of X171 column is =
 [0 1]

The no. of unique values of X172 column is = 2
  & unique values of X172 column is =
 [0 1]

The no. of unique values of X173 column is = 2
  & unique values of X173 column is =
 [0 1]

The no. of unique values of X174 column is = 2
  & unique values of X174 column is =
 [0 1]

The no. of unique values of X175 column is = 2
  & unique values of X175 column is =
 [0 1]

The no. of unique values of X176 column is = 2
  & unique values of X176 column is =
 [0 1]

The no. of unique values of X177 column is = 2
  & unique values of X177 column is =
 [0 1]

The no. of unique values of X178 column is = 2
  & unique values of X178 column is =
 [0 1]

The no. of unique values of X179 column is = 2
  & unique values of X179 column is =
 [1 0]

The no. of unique values of X180 column is = 2
  & unique values of X180 column is =
 [0 1]

The no. of unique values of X181 column is = 2
  & unique values of X181 column is =
 [0 1]

The no. of unique values of X182 column is = 2
  & unique values of X182 column is =
 [0 1]

The no. of unique values of X183 column is = 2
  & unique values of X183 column is =
 [0 1]

The no. of unique values of X184 column is = 2
  & unique values of X184 column is =
 [0 1]

The no. of unique values of X185 column is = 2
  & unique values of X185 column is =
 [1 0]

The no. of unique values of X186 column is = 2
  & unique values of X186 column is =
 [0 1]

The no. of unique values of X187 column is = 2
  & unique values of X187 column is =
 [0 1]

The no. of unique values of X189 column is = 2
  & unique values of X189 column is =
 [0 1]

The no. of unique values of X190 column is = 2
  & unique values of X190 column is =
 [0 1]

The no. of unique values of X191 column is = 2
  & unique values of X191 column is =
 [0 1]

The no. of unique values of X192 column is = 2
  & unique values of X192 column is =
 [0 1]

The no. of unique values of X194 column is = 2
  & unique values of X194 column is =
 [1 0]

The no. of unique values of X195 column is = 2
  & unique values of X195 column is =
 [0 1]

The no. of unique values of X196 column is = 2
  & unique values of X196 column is =
 [0 1]

The no. of unique values of X197 column is = 2
  & unique values of X197 column is =
 [0 1]

The no. of unique values of X198 column is = 2
  & unique values of X198 column is =
 [0 1]

The no. of unique values of X199 column is = 2
  & unique values of X199 column is =
 [0 1]

The no. of unique values of X200 column is = 2
  & unique values of X200 column is =
 [0 1]

The no. of unique values of X201 column is = 2
  & unique values of X201 column is =
 [0 1]

The no. of unique values of X202 column is = 2
  & unique values of X202 column is =
 [0 1]

The no. of unique values of X203 column is = 2
  & unique values of X203 column is =
 [0 1]

The no. of unique values of X204 column is = 2
  & unique values of X204 column is =
 [1 0]

The no. of unique values of X205 column is = 2
  & unique values of X205 column is =
 [0 1]

The no. of unique values of X206 column is = 2
  & unique values of X206 column is =
 [0 1]

The no. of unique values of X207 column is = 2
  & unique values of X207 column is =
 [0 1]

The no. of unique values of X208 column is = 2
  & unique values of X208 column is =
 [0 1]

The no. of unique values of X209 column is = 2
  & unique values of X209 column is =
 [1 0]

The no. of unique values of X210 column is = 2
  & unique values of X210 column is =
 [0 1]

The no. of unique values of X211 column is = 2
  & unique values of X211 column is =
 [0 1]

The no. of unique values of X212 column is = 2
  & unique values of X212 column is =
 [0 1]

The no. of unique values of X213 column is = 2
  & unique values of X213 column is =
 [0 1]

The no. of unique values of X214 column is = 2
  & unique values of X214 column is =
 [0 1]

The no. of unique values of X215 column is = 2
  & unique values of X215 column is =
 [0 1]

The no. of unique values of X216 column is = 2
  & unique values of X216 column is =
 [0 1]

The no. of unique values of X217 column is = 2
  & unique values of X217 column is =
 [0 1]

The no. of unique values of X218 column is = 2
  & unique values of X218 column is =
 [1 0]

The no. of unique values of X219 column is = 2
  & unique values of X219 column is =
 [0 1]

The no. of unique values of X220 column is = 2
  & unique values of X220 column is =
 [1 0]

The no. of unique values of X221 column is = 2
  & unique values of X221 column is =
 [0 1]

The no. of unique values of X222 column is = 2
  & unique values of X222 column is =
 [0 1]

The no. of unique values of X223 column is = 2
  & unique values of X223 column is =
 [1 0]

The no. of unique values of X224 column is = 2
  & unique values of X224 column is =
 [0 1]

The no. of unique values of X225 column is = 2
  & unique values of X225 column is =
 [0 1]

The no. of unique values of X226 column is = 2
  & unique values of X226 column is =
 [0 1]

The no. of unique values of X227 column is = 2
  & unique values of X227 column is =
 [0 1]

The no. of unique values of X228 column is = 2
  & unique values of X228 column is =
 [0 1]

The no. of unique values of X229 column is = 2
  & unique values of X229 column is =
 [0 1]

The no. of unique values of X230 column is = 2
  & unique values of X230 column is =
 [0 1]

The no. of unique values of X231 column is = 2
  & unique values of X231 column is =
 [0 1]

The no. of unique values of X232 column is = 2
  & unique values of X232 column is =
 [1 0]

The no. of unique values of X234 column is = 2
  & unique values of X234 column is =
 [0 1]

The no. of unique values of X236 column is = 2
  & unique values of X236 column is =
 [0 1]

The no. of unique values of X237 column is = 2
  & unique values of X237 column is =
 [0 1]

The no. of unique values of X238 column is = 2
  & unique values of X238 column is =
 [0 1]

The no. of unique values of X239 column is = 2
  & unique values of X239 column is =
 [0 1]

The no. of unique values of X240 column is = 2
  & unique values of X240 column is =
 [0 1]

The no. of unique values of X241 column is = 2
  & unique values of X241 column is =
 [0 1]

The no. of unique values of X242 column is = 2
  & unique values of X242 column is =
 [0 1]

The no. of unique values of X243 column is = 2
  & unique values of X243 column is =
 [0 1]

The no. of unique values of X244 column is = 2
  & unique values of X244 column is =
 [0 1]

The no. of unique values of X245 column is = 2
  & unique values of X245 column is =
 [0 1]

The no. of unique values of X246 column is = 2
  & unique values of X246 column is =
 [1 0]

The no. of unique values of X247 column is = 2
  & unique values of X247 column is =
 [0 1]

The no. of unique values of X248 column is = 2
  & unique values of X248 column is =
 [0 1]

The no. of unique values of X249 column is = 2
  & unique values of X249 column is =
 [0 1]

The no. of unique values of X250 column is = 2
  & unique values of X250 column is =
 [1 0]

The no. of unique values of X251 column is = 2
  & unique values of X251 column is =
 [0 1]

The no. of unique values of X252 column is = 2
  & unique values of X252 column is =
 [0 1]

The no. of unique values of X253 column is = 2
  & unique values of X253 column is =
 [0 1]

The no. of unique values of X254 column is = 2
  & unique values of X254 column is =
 [0 1]

The no. of unique values of X255 column is = 2
  & unique values of X255 column is =
 [0 1]

The no. of unique values of X256 column is = 2
  & unique values of X256 column is =
 [1 0]

The no. of unique values of X257 column is = 1
  & unique values of X257 column is =
 [0]

The no. of unique values of X258 column is = 1
  & unique values of X258 column is =
 [0]

The no. of unique values of X259 column is = 2
  & unique values of X259 column is =
 [0 1]

The no. of unique values of X260 column is = 2
  & unique values of X260 column is =
 [0 1]

The no. of unique values of X261 column is = 2
  & unique values of X261 column is =
 [0 1]

The no. of unique values of X262 column is = 2
  & unique values of X262 column is =
 [0 1]

The no. of unique values of X263 column is = 2
  & unique values of X263 column is =
 [0 1]

The no. of unique values of X264 column is = 2
  & unique values of X264 column is =
 [0 1]

The no. of unique values of X265 column is = 2
  & unique values of X265 column is =
 [0 1]

The no. of unique values of X266 column is = 2
  & unique values of X266 column is =
 [0 1]

The no. of unique values of X267 column is = 2
  & unique values of X267 column is =
 [0 1]

The no. of unique values of X269 column is = 2
  & unique values of X269 column is =
 [0 1]

The no. of unique values of X270 column is = 2
  & unique values of X270 column is =
 [0 1]

The no. of unique values of X271 column is = 2
  & unique values of X271 column is =
 [0 1]

The no. of unique values of X272 column is = 2
  & unique values of X272 column is =
 [1 0]

The no. of unique values of X273 column is = 2
  & unique values of X273 column is =
 [1 0]

The no. of unique values of X274 column is = 2
  & unique values of X274 column is =
 [0 1]

The no. of unique values of X275 column is = 2
  & unique values of X275 column is =
 [0 1]

The no. of unique values of X276 column is = 2
  & unique values of X276 column is =
 [1 0]

The no. of unique values of X277 column is = 2
  & unique values of X277 column is =
 [0 1]

The no. of unique values of X278 column is = 2
  & unique values of X278 column is =
 [0 1]

The no. of unique values of X279 column is = 2
  & unique values of X279 column is =
 [1 0]

The no. of unique values of X280 column is = 2
  & unique values of X280 column is =
 [0 1]

The no. of unique values of X281 column is = 2
  & unique values of X281 column is =
 [0 1]

The no. of unique values of X282 column is = 2
  & unique values of X282 column is =
 [0 1]

The no. of unique values of X283 column is = 2
  & unique values of X283 column is =
 [0 1]

The no. of unique values of X284 column is = 2
  & unique values of X284 column is =
 [0 1]

The no. of unique values of X285 column is = 2
  & unique values of X285 column is =
 [0 1]

The no. of unique values of X286 column is = 2
  & unique values of X286 column is =
 [1 0]

The no. of unique values of X287 column is = 2
  & unique values of X287 column is =
 [0 1]

The no. of unique values of X288 column is = 2
  & unique values of X288 column is =
 [0 1]

The no. of unique values of X291 column is = 2
  & unique values of X291 column is =
 [0 1]

The no. of unique values of X292 column is = 2
  & unique values of X292 column is =
 [0 1]

The no. of unique values of X294 column is = 2
  & unique values of X294 column is =
 [0 1]

The no. of unique values of X295 column is = 1
  & unique values of X295 column is =
 [0]

The no. of unique values of X296 column is = 1
  & unique values of X296 column is =
 [0]

The no. of unique values of X298 column is = 2
  & unique values of X298 column is =
 [0 1]

The no. of unique values of X299 column is = 2
  & unique values of X299 column is =
 [0 1]

The no. of unique values of X300 column is = 2
  & unique values of X300 column is =
 [0 1]

The no. of unique values of X301 column is = 2
  & unique values of X301 column is =
 [0 1]

The no. of unique values of X302 column is = 2
  & unique values of X302 column is =
 [0 1]

The no. of unique values of X304 column is = 2
  & unique values of X304 column is =
 [1 0]

The no. of unique values of X305 column is = 2
  & unique values of X305 column is =
 [0 1]

The no. of unique values of X306 column is = 2
  & unique values of X306 column is =
 [0 1]

The no. of unique values of X307 column is = 2
  & unique values of X307 column is =
 [0 1]

The no. of unique values of X308 column is = 2
  & unique values of X308 column is =
 [0 1]

The no. of unique values of X309 column is = 2
  & unique values of X309 column is =
 [0 1]

The no. of unique values of X310 column is = 2
  & unique values of X310 column is =
 [0 1]

The no. of unique values of X311 column is = 2
  & unique values of X311 column is =
 [0 1]

The no. of unique values of X312 column is = 2
  & unique values of X312 column is =
 [0 1]

The no. of unique values of X313 column is = 2
  & unique values of X313 column is =
 [0 1]

The no. of unique values of X314 column is = 2
  & unique values of X314 column is =
 [0 1]

The no. of unique values of X315 column is = 2
  & unique values of X315 column is =
 [0 1]

The no. of unique values of X316 column is = 2
  & unique values of X316 column is =
 [0 1]

The no. of unique values of X317 column is = 2
  & unique values of X317 column is =
 [0 1]

The no. of unique values of X318 column is = 2
  & unique values of X318 column is =
 [0 1]

The no. of unique values of X319 column is = 2
  & unique values of X319 column is =
 [0 1]

The no. of unique values of X320 column is = 2
  & unique values of X320 column is =
 [0 1]

The no. of unique values of X321 column is = 2
  & unique values of X321 column is =
 [0 1]

The no. of unique values of X322 column is = 2
  & unique values of X322 column is =
 [0 1]

The no. of unique values of X323 column is = 2
  & unique values of X323 column is =
 [0 1]

The no. of unique values of X324 column is = 2
  & unique values of X324 column is =
 [0 1]

The no. of unique values of X325 column is = 2
  & unique values of X325 column is =
 [0 1]

The no. of unique values of X326 column is = 2
  & unique values of X326 column is =
 [0 1]

The no. of unique values of X327 column is = 2
  & unique values of X327 column is =
 [0 1]

The no. of unique values of X328 column is = 2
  & unique values of X328 column is =
 [1 0]

The no. of unique values of X329 column is = 2
  & unique values of X329 column is =
 [0 1]

The no. of unique values of X331 column is = 2
  & unique values of X331 column is =
 [0 1]

The no. of unique values of X332 column is = 2
  & unique values of X332 column is =
 [0 1]

The no. of unique values of X333 column is = 2
  & unique values of X333 column is =
 [0 1]

The no. of unique values of X334 column is = 2
  & unique values of X334 column is =
 [1 0]

The no. of unique values of X335 column is = 2
  & unique values of X335 column is =
 [0 1]

The no. of unique values of X336 column is = 2
  & unique values of X336 column is =
 [0 1]

The no. of unique values of X337 column is = 2
  & unique values of X337 column is =
 [0 1]

The no. of unique values of X338 column is = 2
  & unique values of X338 column is =
 [0 1]

The no. of unique values of X339 column is = 2
  & unique values of X339 column is =
 [0 1]

The no. of unique values of X340 column is = 2
  & unique values of X340 column is =
 [0 1]

The no. of unique values of X341 column is = 2
  & unique values of X341 column is =
 [0 1]

The no. of unique values of X342 column is = 2
  & unique values of X342 column is =
 [0 1]

The no. of unique values of X343 column is = 2
  & unique values of X343 column is =
 [0 1]

The no. of unique values of X344 column is = 2
  & unique values of X344 column is =
 [0 1]

The no. of unique values of X345 column is = 2
  & unique values of X345 column is =
 [0 1]

The no. of unique values of X346 column is = 2
  & unique values of X346 column is =
 [0 1]

The no. of unique values of X348 column is = 2
  & unique values of X348 column is =
 [1 0]

The no. of unique values of X349 column is = 2
  & unique values of X349 column is =
 [0 1]

The no. of unique values of X350 column is = 2
  & unique values of X350 column is =
 [1 0]

The no. of unique values of X351 column is = 2
  & unique values of X351 column is =
 [0 1]

The no. of unique values of X352 column is = 2
  & unique values of X352 column is =
 [0 1]

The no. of unique values of X353 column is = 2
  & unique values of X353 column is =
 [0 1]

The no. of unique values of X354 column is = 2
  & unique values of X354 column is =
 [0 1]

The no. of unique values of X355 column is = 2
  & unique values of X355 column is =
 [0 1]

The no. of unique values of X356 column is = 2
  & unique values of X356 column is =
 [0 1]

The no. of unique values of X357 column is = 2
  & unique values of X357 column is =
 [0 1]

The no. of unique values of X358 column is = 2
  & unique values of X358 column is =
 [1 0]

The no. of unique values of X359 column is = 2
  & unique values of X359 column is =
 [0 1]

The no. of unique values of X360 column is = 2
  & unique values of X360 column is =
 [0 1]

The no. of unique values of X361 column is = 2
  & unique values of X361 column is =
 [1 0]

The no. of unique values of X362 column is = 2
  & unique values of X362 column is =
 [0 1]

The no. of unique values of X363 column is = 2
  & unique values of X363 column is =
 [1 0]

The no. of unique values of X364 column is = 2
  & unique values of X364 column is =
 [0 1]

The no. of unique values of X365 column is = 2
  & unique values of X365 column is =
 [0 1]

The no. of unique values of X366 column is = 2
  & unique values of X366 column is =
 [0 1]

The no. of unique values of X367 column is = 2
  & unique values of X367 column is =
 [0 1]

The no. of unique values of X368 column is = 2
  & unique values of X368 column is =
 [0 1]

The no. of unique values of X369 column is = 1
  & unique values of X369 column is =
 [0]

The no. of unique values of X370 column is = 2
  & unique values of X370 column is =
 [0 1]

The no. of unique values of X371 column is = 2
  & unique values of X371 column is =
 [0 1]

The no. of unique values of X372 column is = 2
  & unique values of X372 column is =
 [0 1]

The no. of unique values of X373 column is = 2
  & unique values of X373 column is =
 [0 1]

The no. of unique values of X374 column is = 2
  & unique values of X374 column is =
 [0 1]

The no. of unique values of X375 column is = 2
  & unique values of X375 column is =
 [0 1]

The no. of unique values of X376 column is = 2
  & unique values of X376 column is =
 [0 1]

The no. of unique values of X377 column is = 2
  & unique values of X377 column is =
 [0 1]

The no. of unique values of X378 column is = 2
  & unique values of X378 column is =
 [1 0]

The no. of unique values of X379 column is = 2
  & unique values of X379 column is =
 [0 1]

The no. of unique values of X380 column is = 2
  & unique values of X380 column is =
 [0 1]

The no. of unique values of X382 column is = 2
  & unique values of X382 column is =
 [0 1]

The no. of unique values of X383 column is = 2
  & unique values of X383 column is =
 [0 1]

The no. of unique values of X384 column is = 2
  & unique values of X384 column is =
 [0 1]

The no. of unique values of X385 column is = 2
  & unique values of X385 column is =
 [0 1]

In [21]:
# making DataFrame accoeding to unique value
test_unique_info =pd.DataFrame({"columns":columns_test, 
                                 "counts":counts_test,
                                 "unique":unique_test})

In [22]:
test_unique_info.head()

  columns  counts                                             unique
0      ID    4209  [1, 2, 3, 4, 5, 8, 10, 11, 12, 14, 15, 16, 17,...
1      X0      49  [az, t, w, y, x, f, ap, o, ay, al, h, z, aj, d...
2      X1      27  [v, b, l, s, aa, r, a, i, p, c, o, m, z, e, h,...
3      X2      45  [n, ai, as, ae, s, b, e, ak, m, a, aq, ag, r, ...
4      X3       7                              [f, a, c, e, d, g, b]

### 3. Apply label encoder.

In [23]:
train.info(verbose=True)
# X0      object
# X1      object
# X2      object
# X3      object
# X4      object
# X5      object
# X6      object
# X8      object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 366 columns):
ID      int64
y       float64
X0      object
X1      object
X2      object
X3      object
X4      object
X5      object
X6      object
X8      object
X10     int64
X12     int64
X13     int64
X14     int64
X15     int64
X16     int64
X17     int64
X18     int64
X19     int64
X20     int64
X21     int64
X22     int64
X23     int64
X24     int64
X26     int64
X27     int64
X28     int64
X29     int64
X30     int64
X31     int64
X32     int64
X33     int64
X34     int64
X35     int64
X36     int64
X37     int64
X38     int64
X39     int64
X40     int64
X41     int64
X42     int64
X43     int64
X44     int64
X45     int64
X46     int64
X47     int64
X48     int64
X49     int64
X50     int64
X51     int64
X52     int64
X53     int64
X54     int64
X55     int64
X56     int64
X57     int64
X58     int64
X59     int64
X60     int64
X61     int64
X62     int64
X63     int64
X64     int64
X65     int64
X66     int64
X67     int64
X68     int64
X69     int64
X70     int64
X71     int64
X73     int64
X74     int64
X75     int64
X76     int64
X77     int64
X78     int64
X79     int64
X80     int64
X81     int64
X82     int64
X83     int64
X84     int64
X85     int64
X86     int64
X87     int64
X88     int64
X89     int64
X90     int64
X91     int64
X92     int64
X94     int64
X95     int64
X96     int64
X97     int64
X98     int64
X99     int64
X100    int64
X101    int64
X102    int64
X103    int64
X104    int64
X105    int64
X106    int64
X108    int64
X109    int64
X110    int64
X111    int64
X112    int64
X113    int64
X114    int64
X115    int64
X116    int64
X117    int64
X118    int64
X119    int64
X120    int64
X122    int64
X123    int64
X124    int64
X125    int64
X126    int64
X127    int64
X128    int64
X129    int64
X130    int64
X131    int64
X132    int64
X133    int64
X134    int64
X135    int64
X136    int64
X137    int64
X138    int64
X139    int64
X140    int64
X141    int64
X142    int64
X143    int64
X144    int64
X145    int64
X146    int64
X147    int64
X148    int64
X150    int64
X151    int64
X152    int64
X153    int64
X154    int64
X155    int64
X156    int64
X157    int64
X158    int64
X159    int64
X160    int64
X161    int64
X162    int64
X163    int64
X164    int64
X165    int64
X166    int64
X167    int64
X168    int64
X169    int64
X170    int64
X171    int64
X172    int64
X173    int64
X174    int64
X175    int64
X176    int64
X177    int64
X178    int64
X179    int64
X180    int64
X181    int64
X182    int64
X183    int64
X184    int64
X185    int64
X186    int64
X187    int64
X189    int64
X190    int64
X191    int64
X192    int64
X194    int64
X195    int64
X196    int64
X197    int64
X198    int64
X199    int64
X200    int64
X201    int64
X202    int64
X203    int64
X204    int64
X205    int64
X206    int64
X207    int64
X208    int64
X209    int64
X210    int64
X211    int64
X212    int64
X213    int64
X214    int64
X215    int64
X216    int64
X217    int64
X218    int64
X219    int64
X220    int64
X221    int64
X222    int64
X223    int64
X224    int64
X225    int64
X226    int64
X227    int64
X228    int64
X229    int64
X230    int64
X231    int64
X232    int64
X234    int64
X236    int64
X237    int64
X238    int64
X239    int64
X240    int64
X241    int64
X242    int64
X243    int64
X244    int64
X245    int64
X246    int64
X247    int64
X248    int64
X249    int64
X250    int64
X251    int64
X252    int64
X253    int64
X254    int64
X255    int64
X256    int64
X257    int64
X258    int64
X259    int64
X260    int64
X261    int64
X262    int64
X263    int64
X264    int64
X265    int64
X266    int64
X267    int64
X269    int64
X270    int64
X271    int64
X272    int64
X273    int64
X274    int64
X275    int64
X276    int64
X277    int64
X278    int64
X279    int64
X280    int64
X281    int64
X282    int64
X283    int64
X284    int64
X285    int64
X286    int64
X287    int64
X288    int64
X291    int64
X292    int64
X294    int64
X295    int64
X296    int64
X298    int64
X299    int64
X300    int64
X301    int64
X302    int64
X304    int64
X305    int64
X306    int64
X307    int64
X308    int64
X309    int64
X310    int64
X311    int64
X312    int64
X313    int64
X314    int64
X315    int64
X316    int64
X317    int64
X318    int64
X319    int64
X320    int64
X321    int64
X322    int64
X323    int64
X324    int64
X325    int64
X326    int64
X327    int64
X328    int64
X329    int64
X331    int64
X332    int64
X333    int64
X334    int64
X335    int64
X336    int64
X337    int64
X338    int64
X339    int64
X340    int64
X341    int64
X342    int64
X343    int64
X344    int64
X345    int64
X346    int64
X348    int64
X349    int64
X350    int64
X351    int64
X352    int64
X353    int64
X354    int64
X355    int64
X356    int64
X357    int64
X358    int64
X359    int64
X360    int64
X361    int64
X362    int64
X363    int64
X364    int64
X365    int64
X366    int64
X367    int64
X368    int64
X369    int64
X370    int64
X371    int64
X372    int64
X373    int64
X374    int64
X375    int64
X376    int64
X377    int64
X378    int64
X379    int64
X380    int64
X382    int64
X383    int64
X384    int64
X385    int64
dtypes: float64(1), int64(357), object(8)
memory usage: 11.8+ MB

In [24]:
features = train.iloc[:,2:].values
label = train.iloc[:,1].values
test = Test.iloc[:,1:].values
features

array([['k', 'v', 'at', ..., 0, 0, 0],
       ['k', 't', 'av', ..., 0, 0, 0],
       ['az', 'w', 'n', ..., 0, 0, 0],
       ...,
       ['ak', 'v', 'r', ..., 0, 0, 0],
       ['al', 'r', 'e', ..., 0, 0, 0],
       ['z', 'r', 'ae', ..., 0, 0, 0]], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
LE = LabelEncoder()
features[:,0] = LE.fit_transform(features[:,0])
features[:,1] = LE.fit_transform(features[:,1])
features[:,2] = LE.fit_transform(features[:,2])
features[:,3] = LE.fit_transform(features[:,3])
features[:,4] = LE.fit_transform(features[:,4])
features[:,5] = LE.fit_transform(features[:,5])
features[:,6] = LE.fit_transform(features[:,6])
features[:,7] = LE.fit_transform(features[:,7])
features
test[:,0] = LE.fit_transform(test[:,0])
test[:,1] = LE.fit_transform(test[:,1])
test[:,2] = LE.fit_transform(test[:,2])
test[:,3] = LE.fit_transform(test[:,3])
test[:,4] = LE.fit_transform(test[:,4])
test[:,5] = LE.fit_transform(test[:,5])
test[:,6] = LE.fit_transform(test[:,6])
test[:,7] = LE.fit_transform(test[:,7])
test

array([[21, 23, 34, ..., 0, 0, 0],
       [42, 3, 8, ..., 0, 0, 0],
       [21, 23, 17, ..., 0, 0, 0],
       ...,
       [47, 23, 17, ..., 0, 0, 0],
       [7, 23, 17, ..., 0, 0, 0],
       [42, 1, 8, ..., 0, 0, 0]], dtype=object)

In [26]:
test.shape

(4209, 364)

In [27]:
features.shape

(4209, 364)

### 4. Perform dimensionality reduction.

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features = sc.fit_transform(features)

In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(features,label)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [30]:
pca.explained_variance_ratio_

array([0.06892669, 0.05688412, 0.04537457])

In [31]:
features1 = pca.transform(features)

### 5 Predict your test_df values using xgboost

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(features1 ,
                                                 label , 
                                                 test_size = 0.2,
                                                 random_state = 1)

In [33]:
from xgboost import XGBRFRegressor
xgb = XGBRFRegressor()
xgb.fit(features1,label)

[16:37:37] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRFRegressor(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
               colsample_bytree=1, gamma=0, learning_rate=1, max_delta_step=0,
               max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
               n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
               silent=None, subsample=0.8, verbosity=1)

In [34]:
xgb.score(features1,label)

0.23688570776320028

In [35]:
xgb.score(x_test,y_test)

0.24085395877279092

### Test

In [36]:
t=sc.transform(test)
test1=pca.transform(t)

xgb.predict(test1)

array([ 77.485634, 103.923965,  77.485634, ..., 102.710686, 102.710686,
        99.05701 ], dtype=float32)

#### hence variance is not greater than 70%  or  not greater than  50%

####  Quality of model is not good

## 5 .Predict your test_df values using xgboost

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=1)

In [38]:
from xgboost import XGBRFRegressor
model = XGBRFRegressor()
model.fit(X_train,y_train)

[16:37:39] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRFRegressor(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
               colsample_bytree=1, gamma=0, learning_rate=1, max_delta_step=0,
               max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
               n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
               reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
               silent=None, subsample=0.8, verbosity=1)

In [39]:
#Check the Quality of the model
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.5579728624404683
0.5835283609616132

In [40]:
model.predict(test)

array([108.26955 ,  94.1049  , 108.26955 , ...,  94.1049  , 112.576195,
        94.1049  ], dtype=float32)